
#ifndef EXTERNALSHAREDLIB_GLOBAL_H
#define EXTERNALSHAREDLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXTERNALSHAREDLIB_LIBRARY)
#  define EXTERNALSHAREDLIB_EXPORT Q_DECL_EXPORT
#else
#  define EXTERNALSHAREDLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // EXTERNALSHAREDLIB_GLOBAL_H
